apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-ticker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: stock-ticker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-ticker
                port:
                  number: 80

